<a href="https://colab.research.google.com/github/MohamedTolba1199/Tensorflow/blob/main/Tensorflow_Version1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

It use version 2 from Tensorflow by default.

In [3]:
tf.compat.v1.disable_eager_execution()

In [4]:
#definition  or graph
x= tf.constant('Tensorflow')
print(x)
# the result not apeared, shouls open session and run it

Tensor("Const:0", shape=(), dtype=string)


In [5]:
#session or execution
sess=tf.compat.v1.Session()
s=sess.run(x)
print(s)
sess.close()

b'Tensorflow'


In [6]:
# definition or graph
x=tf.constant(6)
y=tf.constant(10)

z=tf.add(x,y)
print(z)

Tensor("Add:0", shape=(), dtype=int32)


In [7]:
#session or execution
sess=tf.compat.v1.Session()
s=sess.run(z)
print(s)
sess.close()

16


In [8]:
#Another way to open session and close it bydefault when finishin run
with tf.compat.v1.Session() as sess:
    res=sess.run(z)
    print(res)

16


#matrix multiplication using tensorflow

In [9]:
import numpy as np

In [10]:
var1 = np.arange(1,13,dtype=np.int32)
var2 = np.arange(15,27,dtype=np.int32)
var1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)

In [11]:
# you should convert data from any type to tensor to deal with tensorflow
mat1=tf.constant(var1,shape=[3,4])
mat2=tf.constant(var2,shape=[4,3])

c=tf.matmul(mat1,mat2)
c

<tf.Tensor 'MatMul:0' shape=(3, 3) dtype=int32>

In [12]:
var1 = np.arange(1,5,dtype=np.int32)
var2 = np.arange(6,10,dtype=np.int32)
print(var1)
print(var2)

[1 2 3 4]
[6 7 8 9]


#make add,subtract,multiplication,divide using tensorflow

In [13]:
#from keras.engine.training import data_adapter
v1 = tf.constant([1, 2 ,3 ,4])
v2 = tf.constant([6, 7 ,8 ,9])

Add = tf.add(v1,v2)
Sub = tf.subtract(v1,v2)
Mul = tf.multiply(v1,v2)
Div = tf.divide(v1,v2)

with tf.compat.v1.Session() as sess:
  print(sess.run(Add))
  print(sess.run(Sub))
  print(sess.run(Mul))
  print(sess.run(Div))

[ 7  9 11 13]
[-5 -5 -5 -5]
[ 6 14 24 36]
[0.16666667 0.28571429 0.375      0.44444444]


#aplly linear regression using tensorflow

y=wx+b

In [14]:
x_data = np.random.randn(4,9)
w_data = np.random.randn(9,1)
b_data = np.zeros(4)


In [15]:
x= tf.constant(x_data , shape=[4,9])
w= tf.constant(w_data , shape=[9,1])
b= tf.constant(b_data , shape=[4,1])

In [16]:
y=tf.add(tf.matmul(x,w),b)
y

<tf.Tensor 'Add_2:0' shape=(4, 1) dtype=float64>

In [17]:
with tf.compat.v1.Session() as sess:
  print(sess.run(y))

[[-0.74682576]
 [-4.49513396]
 [ 2.87589795]
 [-1.7932378 ]]


Varbile

In [18]:
#name here for it' name in graph
var1 = tf.Variable(12 , name='varaible1')
var2 = tf.Variable(13 , name='varaible2')

In [19]:
#get the name
var1.name

'varaible1:0'

In [20]:
##get the value
# with tf.compat.v1.Session() as sess:
#     print(sess.run(var1))

#error because in variable should make an initailizations

In [21]:
init_var=tf.compat.v1.global_variables_initializer()

In [22]:
with tf.compat.v1.Session() as sess:
 sess.run(init_var)
 print(sess.run(var1))

12


#Apply linear regression but with variable not constant

1- if we used gradient descent to update the value of w,b that mean thier values will be changed, so the code will push error be cause we made thier definition as a constant.

2- so make w,b as a variable.

In [23]:
x= tf.constant([[3],[4],[4]] , shape=[3,1])
w= tf.Variable([[1,2,3]], shape=[1,3])
b= tf.Variable(1)

out = tf.add(tf.matmul(x,w),b)
out

<tf.Tensor 'Add_3:0' shape=(3, 3) dtype=int32>

In [24]:
init_var=tf.compat.v1.global_variables_initializer()

In [25]:
with tf.compat.v1.Session() as sess:
 sess.run(init_var)
 print(sess.run(out))

[[ 4  7 10]
 [ 5  9 13]
 [ 5  9 13]]


#Apply Linear regression and using Gradient Descent to update weight

In [26]:
#original data
x_data=np.array(  [[4,2] , [3,5]  , [4,6] ,[7,3] ] ,dtype='float64' )
y_data=np.array(  [[5]   ,  [7]   ,  [6]  , [9] ] ,dtype='float64' )

In [27]:
#convert original data to tensor
x=tf.constant(x_data)
y=tf.constant(y_data)
w=tf.Variable(np.random.randn(2,1))
b=tf.Variable(np.zeros(4, dtype='float64'))

In [28]:
#initialization
init=tf.compat.v1.global_variables_initializer()

In [29]:
#feedforward
y_pred=tf.add(tf.matmul(x,w),b)
#backward
cost=tf.reduce_mean(tf.square(y_pred-y))#MSE
optimizer=tf.compat.v1.train.GradientDescentOptimizer(learning_rate=.11).minimize(cost)

In [30]:
with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(' the initial weight:')
  print(sess.run(w))

  print(' the first y_pred:')
  print(sess.run(y_pred))

  print('==================================================')

  sess.run(optimizer)

  print(' the updated weight:')
  print(sess.run(w))

  print(' the updated y_pred:')
  print(sess.run(y_pred))

#will noticed that:: the values of weights changed

 the initial weight:
[[ 0.53050176]
 [-0.99182819]]
 the first y_pred:
[[ 0.13835067  0.13835067  0.13835067  0.13835067]
 [-3.36763568 -3.36763568 -3.36763568 -3.36763568]
 [-3.82896211 -3.82896211 -3.82896211 -3.82896211]
 [ 0.73802777  0.73802777  0.73802777  0.73802777]]
 the updated weight:
[[8.65395543]
 [7.00083591]]
 the updated y_pred:
[[49.07564657 49.07564657 49.07564657 49.07564657]
 [61.42419888 61.42419888 61.42419888 61.42419888]
 [77.07899023 77.07899023 77.07899023 77.07899023]
 [82.03834878 82.03834878 82.03834878 82.03834878]]
